name: forecasting
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - attr=2.5.1
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - comm=0.2.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - debugpy=1.8.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - filelock=3.16.1
  - freetype=2.12.1
  - fsspec=2024.10.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - icu=75.1
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.29.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kaldi=5.5.1112
  - keyutils=1.6.1
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libcap=2.69
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.11.1.6
  - libcurand=10.3.7.77
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt=1.11.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libgpg-error=1.50
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnl=3.10.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libopenblas=0.3.28
  - libpng=1.6.44
  - libprotobuf=5.28.2
  - libsodium=1.0.20
  - libsqlite=3.47.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=256.7
  - libtiff=4.7.0
  - libtorch=2.4.1
  - libudev1=256.7
  - libuuid=2.38.1
  - libuv=1.49.2
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nomkl=1.0
  - openfst=1.8.3
  - openjpeg=2.5.2
  - openssl=3.3.2
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.3.1
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.10.15
  - python_abi=3.10
  - pytorch=2.4.1
  - pytorch-cuda=11.8
  - pyzmq=26.2.0
  - rdma-core=54.0
  - readline=8.2
  - setuptools=75.3.0
  - six=1.16.0
  - sleef=3.7
  - sqlite=3.47.0
  - stack_data=0.6.2
  - tk=8.6.13
  - torchaudio=2.4.1
  - torchvision=0.19.1
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - adagio==0.2.6
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==24.2.0
      - cloudpickle==3.1.0
      - contourpy==1.3.0
      - coreforecast==0.0.13.1
      - cycler==0.12.1
      - cython==3.0.11
      - darts==0.31.0
      - fonttools==4.54.1
      - frozenlist==1.5.0
      - fs==2.4.16
      - fugue==0.9.1
      - holidays==0.59
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lightning-utilities==0.11.8
      - llvmlite==0.43.0
      - matplotlib==3.9.2
      - multidict==6.1.0
      - nfoursid==1.0.1
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-nccl-cu12==2.23.4
      - pandas==2.2.3
      - patsy==0.5.6
      - pmdarima==2.0.4
      - propcache==0.2.0
      - protobuf==5.28.3
      - pyarrow==18.0.0
      - pyod==2.0.2
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.4.0
      - pytz==2024.2
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - shap==0.46.0
      - slicer==0.0.8
      - statsforecast==1.7.8
      - statsmodels==0.14.4
      - sympy==1.13.1
      - tbats==1.1.3
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.5.0
      - torchmetrics==1.5.1
      - tqdm==4.66.6
      - triad==0.9.8
      - tzdata==2024.2
      - utilsforecast==0.2.7
      - xarray==2024.10.0
      - xgboost==2.1.2
      - yarl==1.17.1
